# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml/

authors = ["developer@example.com"]
description = "Dynamic Backends proxy service - forwards requests to arbitrary origins"
language = "javascript"
manifest_version = 3
name = "compute-dynbackends-dev"
service_id = "4CYdEwKdz8ZpIPfElRLI0B"

[scripts]
build = "npm run build"

# The "dynserv-key" config store must be linked to this service
# See README.md for setup instructions
