# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml/

authors = ["developer@example.com"]
description = "Dynamic Backends proxy service - forwards requests to arbitrary origins"
language = "rust"
manifest_version = 3
name = "compute-dynbackends-dev"

[scripts]
build = "cargo build --release --target wasm32-wasip1"
